import img from "./logo/Rectangle3909.svg";
import bar from "./logo/bar.svg";
import { NEUTRAL, PRIMARY } from "../Theme/Colors";

export const styles = {
  radio: {
    flexDirection: { sm: "row", xs: "colmun" },
    marginTop: "10px",
    gap: { sm: "40px", xs: "5px" },
  },
  input: {
    display: "flex",
    alignItems: "center",
    pr: { sm: 0, xs: 0 },
    pl: { sm: 0, xs: 0 },
    boxShadow: "2px 2px 60px rgba(179, 179, 179, 0.25);",
    width: { xl: "744px", lg: "744px", md: "744px", sm: "600px" },
    backgroundColor: "#ffff",
    borderRadius: "15px",
  },
  btn: {
    backgroundColor: "#4F9AFF",
    color: "white",
    // width:{xs:'70px'},
    height: { sm: "69px", xs: "40px" },
    boxShadow: "none",
    // borderBottomLeftRadius: 0,
    // borderTopLeftRadius: 0,
    borderRadius: "15px",
    fontSize: { sm: "16px", xs: "12px" },
  },
  linebox: {
    display: "flex",
    gap: "5px",
    alignItems: "center",
    justifyContent: "center",
  },
  srch: {
    marginRight: { sm: "38px", xs: "10px" },
    marginLeft: { sm: "34px", xs: "10px" },
    color: "#A6A6A6",
  },
  bgmain: {
    display: "flex",
    justifyContent: "center",
    alignitems: "center",
    pt: "40px",
    pb: "240px",
    backgroundImage: `url(${img})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
  },
  label: {
    fontWeight: 700,
    fontSize: "18px",
    fontFamily: "GreycliffCF-regular",
    textTransform: "capitalize",
    padding: "20px 0 20px 0",
  },
  card: {
    //    height:'800px'
    mb: "650px",
    boxShadow: "4px 4px 60px rgba(193, 200, 209, 0.25)",
    width: { xs: "95%", sm: "90%" },
  },
  editico: {
    display: "flex",
    justifyContent: "space-between",
    backgroundColor: PRIMARY,
    color: NEUTRAL,
    padding: "10px 5px 10px 15px",
    alignItems: "center",
  },
  toptext: {
    ml: "15px",
    mt: "12px",
    fontSize: "18px",
    fontWeight: "700",
    fontFamily: "arial",
  },
  filetext: {
    fontSize: "14px",
    fontWeight: "700",
    fontFamily: "arial",
    color: "#6A6A6A",
    ml: "15px",
    mt: "8px",
    padding: "20px 0 20px 0",
  },
  download: {
    display: "flex",
    justifyContent: "space-between",
    margin: "20px  17px 17px  17px ",
    backgroundColor: "#EEEEEE",
    borderRadius: "8px",
  },
  frsttab: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    pb: "10px",
  },
  personal: {
    display: "flex",
    justifyContent: "space-between",
    p: "10px 5px 10px 15px",
    fontSize: "14px",
    fontWeight: "700",
    fontFamily: "arial",
    backgroundColor: PRIMARY,
    color: NEUTRAL,
    alignItems: "center",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  worktext: {
    fontSize: "18px",
    fontWeight: "800",
    fontFamily: "arial",
  },
  expico: {
    border: "1px solid #CACACA",
    borderRadius: "8px",
    marginLeft: "15px",
  },
  jobtitle: {
    display: "flex",
    justifyContent: "space-between",
    pt: "20px",
    alignItems: "center",
  },
  workmain: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  rolewrk: {
    fontSize: "18px",
    fontWeight: "800",
    fontFamily: "arial",
    lineHeight: "30px",
  },
  locwork: {
    display: "flex",
    alignItems: "center",
    color: "#6A6A6A",
    gap: "22px",
    mt: "20px",
  },
  addbtn: {
    color: "#4F9AFF",
    width: "190px",
    height: "60px",
    mt: "16px",
    textTransform: "capitalize",
    gap: "15px",
  },
  skilltitle: {
    display: "flex",
    justifyContent: "space-between",
    pt: "20px",
    ml: "14px",
    alignItems: "center",
  },
  skilname: {
    fontSize: "16px",
    fontWeight: "700",
    fontFamily: "arial",
  },
  skills: {
    display: "flex",
    justifyContent: "space-between",
    ml: "14px",
    alignItems: "center",
    pr: "10px",
  },
  bar: {
    backgroundImage: `url(${bar})`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    ml: "14px",
  },
  viewbtn: {
    color: "#4F9AFF",
    textTransform: "capitalize",
    ml: "7px",
    gap: "5px",
    mt: "25px",
    pb: "228px",
  },
  eduico: {
    color: "#4F9AFF",
    fontSize: "2em",
    ml: "14px",
  },
  linkpro: {
    display: "flex",
    ml: "14px",
    gap: "12px",
    alignItems: "center",
    pb: "10px",
  },
  prolink: {
    textDecoration: "none",
    color: "#4F9AFF",
    fontSize: "16px",
    fontWeight: "700",
    fontFamily: "arial",
    mb: "2px",
  },
};
