import curve from ".//logo/curve.svg";

export const styles = {
  title: {
    fontSize: "38px",
    fontWeight: "700",
    lineHeight: "70px",
    letterSpacing: "0em",
    textAlign: "center",
    color: "#4F9AFF",
    paddingTop: "88px",
  },
  input: {
    display: "flex",
    alignItems: "center",
    marginTop: "52px",
    pr: { sm: 0, xs: 1 },
    pl: { sm: 0, xs: 1 },
    // marginBottom:'115px',
    // height:'62px',
    boxShadow: "2px 2px 60px rgba(179, 179, 179, 0.25);",
    // boxShadow:2,
    width: { xl: "744px", lg: "744px", md: "744px", sm: "600px" },
  },
  boxmain: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundImage: { sm: `url(${curve})`, xs: "none" },
    backgroundRepeat: "no-repeat",
    backgroundPosition: "left 105% bottom 45%",
  },
  btn: {
    backgroundColor: "#4F9AFF",
    color: "white",
    width: { sm: "168px", xs: "70px" },
    height: { sm: "60px", xs: "40px" },
    boxShadow: "none",
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
    fontSize: { sm: "16px", xs: "12px" },
  },
  srch: {
    marginRight: { sm: "38px", xs: "10px" },
    marginLeft: { sm: "34px", xs: "10px" },
    color: "#A6A6A6",
  },
  radio: {
    flexDirection: "row",
    marginTop: "26px",
    marginBottom: "30px",
    gap: { sm: "40px", xs: "5px" },
  },
  myProfileStyles: {
    marginBottom: "-127px",
    zIndex: 1,
    color: "white",
    fontWeight: 600,
    position: "absolute",
    display: "flex",
    alignItems: "center",
    marginTop: "52px",
    pr: { sm: 0, xs: 1 },
    pl: { sm: 0, xs: 1 },
    backgroundColor: "white",
    boxShadow: "2px 2px 60px rgba(179, 179, 179, 0.25);",
    width: { xl: "744px", lg: "744px", md: "744px", sm: "600px" },
  },
};
