export const styles = {
    title: {
      paddingTop: "80px",
      fontFamily: "arial",
      fontSize: "36px",
      fontWeight: 700,
      lineHeight: "41px",
      textAlign: "left",
    },
    para: {
      fontFamily: "GreycliffCF-Regular",
      fontWeight: "400",
      fontSize: "20px",
      lineHeight: "25px",
      color: "#6A6A6A",
      marginTop: "8px",
    },
    card: {
      width: "302px",
      height: "180px",
      boxShadow: "4px 4px 60px rgba(173, 183, 196, 0.25)",
    },
    rightcard: {
      // overflowY:'scroll',
      mb: "110px",
    },
    icobox: {
      display: "flex",
      justifyContent: "space-between",
      padding: "12px 12px 0 12px",
      color: "#CACACA",
    },
    cardttle: {
      fontFamily: "arial",
      fontWeight: "800",
      fontSize: "16px",
      lineHeight: "18px",
    },
    cardpara: {
      color: "#6A6A6A",
      fontFamily: "arial",
      fontWeight: "400",
      fontSize: "12px",
      lineHeight: "14px",
    },
    contnt: {
      display: "flex",
      flexDirection: "column",
      gap: "15px",
      padding: "0 17px 0 17px",
    },
    txts: {
      marginTop: "25px",
    },
    crdbtn: {
      backgroundColor: "#4F9AFF",
      textTransform: "capitalize",
    },
    cards: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-around",
      gap: "20px",
      marginTop: "84px",
    },
    jobdetail: {
      height: "auto",
      backgroundColor: "#F6F7FC",
      display: { md: "flex", xs: "none" },
      justifyContent: "space-around",
      flexWrap: "wrap",
    },
    icocrd: {
      width: "90px",
      height: "85px",
      backgroundColor: "#E0EBFC",
      borderRadius: "8px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    icojob: {
      height: "36px",
      width: "36px",
      color: "#4F9AFF",
    },
    cardsdtl: {
      width: "200px",
      height: "85px",
      display: "flex",
      alignItems: "center",
      gap: "20px",
      pt: "85px",
      pb: "85px",
    },
    crdtxt: {
      display: "flex",
      flexDirection: "column",
      gap: "12px",
    },
    numberjobs: {
      fontFamily: "arial",
      fontWeight: "700",
      fontSize: "24px",
      lineHeight: "25px",
    },
    txtjobs: {
      fontFamily: "arial",
      fontWeight: "700",
      fontSize: "16px",
      lineHeight: "18px",
      color: "#6A6A6A",
    },
    headtxt: {
      fontFamily: "GreycliffCF-bold",
      fontWeight: "700",
      fontSize: "32px",
      lineHeight: "45px",
      marginTop: "100px",
    },
    sortbtn: {
      textTransform: "capitalize",
      color: "#6A6A6A",
      width: "150px",
      height: "50px",
      border: "1px solid black",
      borderRadius: "7px",
    },
    sort: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-between",
      gap: "25px",
      pl: { lg: "150px", md: "55px", xs: "2px" },
      paddingRight: { lg: "150px", md: "55px", xs: "2px" },
      marginTop: "5px",
    },
    leftcard: {
      display: "flex",
      flexDirection: { md: "column", xs: "row" },
      gap: "30px",
      alignItems: "center",
      marginRight: "10px",
      height: { md: "1100px", xs: "300px" },
      overflowY: { md: "scroll", xs: "hidden" },
      overflowX: { md: "hidden", xs: "scroll" },
      "&::-webkit-scrollbar": {
        width: "8px",
        color: "#8A8A8A",
        height: "5px",
      },
      "&::-webkit-scrollbar-track": {
        mt: "10px",
        boxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
        webkitBoxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
        backgroundColor: "#D9D9D9",
        borderRadius: "50px",
        height: "5px",
      },
      "&::-webkit-scrollbar-thumb": {
        backgroundColor: "#8A8A8A",
        borderRadius: "50px",
        color: "#8A8A8A",
        // outline: '1px solid slategrey'
      },
      // marginTop:'55px',
      // ml:{lg:'60px',md:'0'}
      // marginBottom:'200px'
    },
    gridcont: {},
    cardslist: {
      paddingRight: "10px",
      display: "flex",
      justifyContent: "center",
      flexBasis: { xs: "0%" },
    },
    maincard: {
      height: "969px",
      // marginTop:'45px',
      marginBottom: { md: "10px", xs: "30px" },
      overflowY: "scroll",
      "&::-webkit-scrollbar": {
        // width: '8px',
        color: "#8A8A8A",
        height: "5px",
      },
      "&::-webkit-scrollbar-track": {
        boxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
        webkitBoxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
        backgroundColor: "#D9D9D9",
        borderRadius: "50px",
        height: "5px",
      },
      "&::-webkit-scrollbar-thumb": {
        backgroundColor: "#8A8A8A",
        borderRadius: "50px",
        color: "#8A8A8A",
      },
    },
    jobico: {
      width: "58px",
      height: "62px",
      border: "1px solid #CACACA",
      padding: "10px 15px 10px 15px",
      borderRadius: "8px",
      marginTop: "8px",
      marginBottom: "15px",
    },
    rolehead: {
      fontFamily: "arial",
      fontWeight: "700",
      fontSize: "21px",
      lineHeight: "26px",
      // marginTop:'8px'
    },
    rolecomp: {
      fontFamily: "GreycliffCF-Regular",
      fontWeight: "700",
      fontSize: "18px",
      lineHeight: "20px",
      color: "#4F9AFF",
    },
    rolecomp1: {
      fontFamily: "GreycliffCF-Regular",
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "24px",
      color: "rgb(115, 115, 115)",
      textTransform: "capitalize",
    },
    icorole: {
      display: "flex",
      gap: "15px",
      justifyContent: "center",
    },
    applybtn: {
      backgroundColor: "#4F9AFF",
      textTransform: "capitalize",
    },
    btngrid: {
      display: "flex",
      justifyContent: { md: "flex-end", xs: "flex-end" },
      alignItems: "center",
      paddingRight: { md: "35px", xs: "15px" },
      pb: { md: "0px", xs: "15px" },
    },
    jobsdetail: {
      fontWeight: "900",
      fontSize: "28px",
      lineHeight: "50px",
      marginTop: "10px",
    },
    detailico: {
      position: "relative",
      top: "5px",
      color: "#4F9AFF",
      mr: "4px",
    },
    detailscard: {
      width: "250px",
      height: "85px",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: "20px",
    },
    jbcrdtitle: {
      fontFamily: "GreycliffCF-Bold",
      fontWeight: "700",
      fontSize: "18px",
      // lineHeight: '40px',
    },
    detailsflx: {
      marginBottom: "57px",
      mt: "45px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-around",
      gap: "15px",
    },
    textjbs: {
      display: "flex",
      flexDirection: "column",
      gap: "15px",
    },
    destination: {
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "50px",
      marginTop: "10px",
      // marginLeft: "30px",
    },
    jobsabout: {
      fontWeight: "700",
      fontSize: "20px",
      lineHeight: "50px",
    },
    list: {
      display: "flex",
      flexDirection: "column",
      gap: "15px",
      marginBottom: "45px",
      color: "#2A2A2A",
    },
    blubtntext: {
      fontSize: "16px",
      fontWeight: "700",
      color: "#4F9AFF",
      fontFamily: "GreycliffCF-Bold",
    },
    bluebtn: {
      height: "47px",
      width: "146px",
      backgroundColor: "#D7E8FF",
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    skillbtns: {
      marginTop: "24px",
      marginLeft: "30px",
      mb: "40px",
      display: "flex",
      justifyContent: "flex-start",
      flexWrap: "wrap",
      gap: "20px",
    },
    lasttext: {
      fontSize: "16px",
      fontWeight: "700",
      color: "#6A6A6A",
      fontFamily: "arial",
      // marginTop:'40px',
      // mb:'24px',
      letterSpacing: "1px",
      marginLeft: "30px",
    },
    linksite: {
      fontSize: "16px",
      fontWeight: "700",
      color: "#6a6a6a",
      fontFamily: "arial",
      textDecoration: "none",
      marginTop: "15px",
      mr: "20px",
    },
    website: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "10px",
      // p:'15px'
      pb: "12px",
      pt: "12px",
    },
    containergrid: {
      display: "flex",
      flexDirection: { md: "row", xs: "row" },
      mt: { lg: "20px", md: "15px", xs: "10px" },
      justifyContent: { md: "center", xs: "none" },
    },
  };
  