export const LANGUAGES = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Asturian",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Catalan",
  "Central Kurdish",
  "Chinese",
  "Chinese (Hong Kong)",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "English (Australia)",
  "English (Canada)",
  "English (India)",
  "English (New Zealand)",
  "English (South Africa)",
  "English (United Kingdom)",
  "English (United States)",
  "Esperanto",
  "Estonian",
  "Faroese",
  "Filipino",
  "Finnish",
  "French",
  "French (Canada)",
  "French (France)",
  "French (Switzerland)",
  "Galician",
  "Georgian",
  "German",
  "German (Austria)",
  "German (Germany)",
  "German (Liechtenstein)",
  "German (Switzerland)",
  "Greek",
  "Guarani",
  "Gujarati",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Interlingua",
  "Irish",
  "Italian",
  "Italian (Italy)",
  "Italian (Switzerland)",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maltese",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Oriya",
  "Oromo",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Romanian (Moldova)",
  "Romansh",
  "Russian",
  "Scottish Gaelic",
  "Serbian",
  "Serbo",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Southern Sotho",
  "Spanish",
  "Spanish (Argentina)",
  "Spanish (Latin America)",
  "Spanish (Mexico)",
  "Spanish (Spain)",
  "Spanish (United States)",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tigrinya",
  "Tongan",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

export const WORK_AVAILABILITY = [
  "Immediately",
  " 1 week",
  "2 weeks",
  "3 weeks",
  "1 month",
  "2 months",
  "3 months",
];

export const USER_EXPERIENCES = [
  "Fresh",
  "Less than 1 year",
  "2 Years",
  "3 Years",
  "4 Years",
  "5 Years",
  "6 Years",
  "7 Years",
  "8 Years +",
  "12 Years +",
  "15 Years +",
  "20 Years +",
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const NATIONALITIES = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];

export const EDUCATION_LEVELS = [
  "Doctorate",
  "Master’s degree",
  "Postgraduate Diploma",
  "Postgraduate Certificate",
  "Graduate with Honors",
  "Bachelor’s degree",
  "Graduate Diploma",
  "Diploma",
  "Certificate",
  "High school",
  "Elementary school",
];

export const CURRENCY = [
  { country: "Afghan Afghani", symbol: "؋" },
  { country: "Albanian Lek", symbol: "Lek" },
  { country: "Algerian Dinar", symbol: "دج" },
  { country: "Angolan Kwanza", symbol: "Kz" },
  { country: "Argentine Peso", symbol: "$" },
  { country: "Armenian Dram", symbol: "֏" },
  { country: "Aruban Florin", symbol: "ƒ" },
  { country: "Australian Dollar", symbol: "$" },
  { country: "Azerbaijani Manat", symbol: "m" },
  { country: "Bahamian Dollar", symbol: "B$" },
  { country: "Bahraini Dinar", symbol: ".د.ب" },
  { country: "Bangladeshi Taka", symbol: "৳" },
  { country: "Barbadian Dollar", symbol: "Bds$" },
  { country: "Belarusian Ruble", symbol: "Br" },
  { country: "Belgian Franc", symbol: "fr" },
  { country: "Belize Dollar", symbol: "$" },
  { country: "Bermudan Dollar", symbol: "$" },
  { country: "Bhutanese Ngultrum", symbol: "Nu." },
  { country: "Bitcoin", symbol: "฿" },
  { country: "Bolivian Boliviano", symbol: "Bs." },
  { country: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { country: "Botswanan Pula", symbol: "P" },
  { country: "Brazilian Real", symbol: "R$" },
  { country: "British Pound Sterling", symbol: "£" },
  { country: "Brunei Dollar", symbol: "B$" },
  { country: "Bulgarian Lev", symbol: "Лв." },
  { country: "Burundian Franc", symbol: "FBu" },
  { country: "Cambodian Riel", symbol: "KHR" },
  { country: "Canadian Dollar", symbol: "$" },
  { country: "Cape Verdean Escudo", symbol: "$" },
  { country: "Cayman Islands Dollar", symbol: "$" },
  { country: "CFA Franc BCEAO", symbol: "CFA" },
  { country: "CFA Franc BEAC", symbol: "FCFA" },
  { country: "CFP Franc", symbol: "₣" },
  { country: "Chilean Peso", symbol: "$" },
  { country: "Chinese Yuan", symbol: "¥" },
  { country: "Colombian Peso", symbol: "$" },
  { country: "Comorian Franc", symbol: "CF" },
  { country: "Congolese Franc", symbol: "FC" },
  { country: "Costa Rican ColÃ³n", symbol: "₡" },
  { country: "Croatian Kuna", symbol: "kn" },
  { country: "Cuban Convertible Peso", symbol: "$CUC" },
  { country: "Czech Republic Koruna", symbol: "Kč" },
  { country: "Danish Krone", symbol: "Kr." },
  { country: "Djiboutian Franc", symbol: "Fdj" },
  { country: "Dominican Peso", symbol: "$" },
  { country: "East Caribbean Dollar", symbol: "$" },
  { country: "Egyptian Pound", symbol: "ج.م" },
  { country: "Eritrean Nakfa", symbol: "Nfk" },
  { country: "Estonian Kroon", symbol: "kr" },
  { country: "Ethiopian Birr", symbol: "Nkf" },
  { country: "Euro", symbol: "€" },
  { country: "Falkland Islands Pound", symbol: "£" },
  { country: "Fijian Dollar", symbol: "FJ$" },
  { country: "Gambian Dalasi", symbol: "D" },
  { country: "Georgian Lari", symbol: "ლ" },
  { country: "German Mark", symbol: "DM" },
  { country: "Ghanaian Cedi", symbol: "GH₵" },
  { country: "Gibraltar Pound", symbol: "£" },
  { country: "Greek Drachma", symbol: "₯, Δρχ, Δρ" },
  { country: "Guatemalan Quetzal", symbol: "Q" },
  { country: "Guinean Franc", symbol: "FG" },
  { country: "Guyanaese Dollar", symbol: "$" },
  { country: "Haitian Gourde", symbol: "G" },
  { country: "Honduran Lempira", symbol: "L" },
  { country: "Hong Kong Dollar", symbol: "$" },
  { country: "Hungarian Forint", symbol: "Ft" },
  { country: "Icelandic KrÃ³na", symbol: "kr" },
  { country: "Indian Rupee", symbol: "₹" },
  { country: "Indonesian Rupiah", symbol: "Rp" },
  { country: "Iranian Rial", symbol: "﷼" },
  { country: "Iraqi Dinar", symbol: "د.ع" },
  { country: "Israeli New Sheqel", symbol: "₪" },
  { country: "Italian Lira", symbol: "L,£" },
  { country: "Jamaican Dollar", symbol: "J$" },
  { country: "Japanese Yen", symbol: "¥" },
  { country: "Jordanian Dinar", symbol: "ا.د" },
  { country: "Kazakhstani Tenge", symbol: "лв" },
  { country: "Kenyan Shilling", symbol: "KSh" },
  { country: "Kuwaiti Dinar", symbol: "ك.د" },
  { country: "Kyrgystani Som", symbol: "лв" },
  { country: "Laotian Kip", symbol: "₭" },
  { country: "Latvian Lats", symbol: "Ls" },
  { country: "Lebanese Pound", symbol: "£" },
  { country: "Lesotho Loti", symbol: "L" },
  { country: "Liberian Dollar", symbol: "$" },
  { country: "Libyan Dinar", symbol: "د.ل" },
  { country: "Lithuanian Litas", symbol: "Lt" },
  { country: "Macanese Pataca", symbol: "$" },
  { country: "Macedonian Denar", symbol: "ден" },
  { country: "Malagasy Ariary", symbol: "Ar" },
  { country: "Malawian Kwacha", symbol: "MK" },
  { country: "Malaysian Ringgit", symbol: "RM" },
  { country: "Maldivian Rufiyaa", symbol: "Rf" },
  { country: "Mauritanian Ouguiya", symbol: "MRU" },
  { country: "Mauritian Rupee", symbol: "₨" },
  { country: "Mexican Peso", symbol: "$" },
  { country: "Moldovan Leu", symbol: "L" },
  { country: "Mongolian Tugrik", symbol: "₮" },
  { country: "Moroccan Dirham", symbol: "MAD" },
  { country: "Mozambican Metical", symbol: "MT" },
  { country: "Myanmar Kyat", symbol: "K" },
  { country: "Namibian Dollar", symbol: "$" },
  { country: "Nepalese Rupee", symbol: "₨" },
  { country: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { country: "New Taiwan Dollar", symbol: "$" },
  { country: "New Zealand Dollar", symbol: "$" },
  { country: "Nicaraguan CÃ³rdoba", symbol: "C$" },
  { country: "Nigerian Naira", symbol: "₦" },
  { country: "North Korean Won", symbol: "₩" },
  { country: "Norwegian Krone", symbol: "kr" },
  { country: "Omani Rial", symbol: ".ع.ر" },
  { country: "Pakistani Rupee", symbol: "₨" },
  { country: "Panamanian Balboa", symbol: "B/." },
  { country: "Papua New Guinean Kina", symbol: "K" },
  { country: "Paraguayan Guarani", symbol: "₲" },
  { country: "Peruvian Nuevo Sol", symbol: "S/." },
  { country: "Philippine Peso", symbol: "₱" },
  { country: "Polish Zloty", symbol: "zł" },
  { country: "Qatari Rial", symbol: "ق.ر" },
  { country: "Romanian Leu", symbol: "lei" },
  { country: "Russian Ruble", symbol: "₽" },
  { country: "Rwandan Franc", symbol: "FRw" },
  { country: "Salvadoran ColÃ³n", symbol: "₡" },
  { country: "Samoan Tala", symbol: "SAT" },
  { country: "Saudi Riyal", symbol: "﷼" },
  { country: "Serbian Dinar", symbol: "din" },
  { country: "Seychellois Rupee", symbol: "SRe" },
  { country: "Sierra Leonean Leone", symbol: "Le" },
  { country: "Singapore Dollar", symbol: "$" },
  { country: "Slovak Koruna", symbol: "Sk" },
  { country: "Solomon Islands Dollar", symbol: "Si$" },
  { country: "Somali Shilling", symbol: "Sh.so." },
  { country: "South African Rand", symbol: "R" },
  { country: "South Korean Won", symbol: "₩" },
  { country: "Special Drawing Rights", symbol: "SDR" },
  { country: "Sri Lankan Rupee", symbol: "Rs" },
  { country: "St. Helena Pound", symbol: "£" },
  { country: "Sudanese Pound", symbol: ".س.ج" },
  { country: "Surinamese Dollar", symbol: "$" },
  { country: "Swazi Lilangeni", symbol: "E" },
  { country: "Swedish Krona", symbol: "kr" },
  { country: "Swiss Franc", symbol: "CHf" },
  { country: "Syrian Pound", symbol: "LS" },
  { country: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { country: "Tajikistani Somoni", symbol: "SM" },
  { country: "Tanzanian Shilling", symbol: "TSh" },
  { country: "Thai Baht", symbol: "฿" },
  { country: "Tongan Pa'anga", symbol: "$" },
  { country: "Trinidad & Tobago Dollar", symbol: "$" },
  { country: "Tunisian Dinar", symbol: "ت.د" },
  { country: "Turkish Lira", symbol: "₺" },
  { country: "Turkmenistani Manat", symbol: "T" },
  { country: "Ugandan Shilling", symbol: "USh" },
  { country: "Ukrainian Hryvnia", symbol: "₴" },
  { country: "United Arab Emirates Dirham", symbol: "إ.د" },
  { country: "Uruguayan Peso", symbol: "$" },
  { country: "US Dollar", symbol: "$" },
  { country: "Uzbekistan Som", symbol: "лв" },
  { country: "Vanuatu Vatu", symbol: "VT" },
  { country: "Venezuelan BolÃvar", symbol: "Bs" },
  { country: "Vietnamese Dong", symbol: "₫" },
  { country: "Yemeni Rial", symbol: "﷼" },
  { country: "Zambian Kwacha", symbol: "ZK" },
];

export const CAREER_LEVEL = [
  "Board",
  "Co-founder/partner",
  "Executives/C-suites",
  "Director/VP",
  "Manager/Senior Manager",
  "Architects/Senior Architects",
  "Tech Lead/Team Leader",
  "Senior Professional",
  "Junior Professional",
  "Fresher",
  "Intern",
];

export const SECTORS = [
  "Aerospace Industry",
  "Transport Industry",
  "Computer Industry",
  "Telecommunication industry",
  "Agriculture industry",
  "Construction Industry",
  "Education Industry",
  "Pharmaceutical Industry",
  "Food Industry",
  " Health care Industry",
  " Hospitality Industry",
  " Entertainment Industry",
  " News Media Industry",
  " Energy Industry",
  " Manufacturing Industry",
  " Music Industry",
  " Mining Industry",
  " Worldwide web",
  " Electronics Industry",
  "Other",
];

export const TIME_ZONES = [
  "UTC-11:00-Midway Island",
  "UTC-10:00-Hawaii",
  "UTC-08:00-Alaska",
  "UTC-07:00-Baja California",
  "UTC-07:00-Pacific Time US and Canada)",
  "UTC-07:00-Arizona",
  "UTC-06:00-Chihuahua",
  "UTC-06:00-Mountain Time US and Canada)",
  "UTC-06:00-Central America",
  "UTC-05:00-Central Time US and Canada)	",
  "UTC-05:00-Guadalajara",
  "UTC-06:00-Saskatchewan",
  "UTC-05:00-Bogota",
  "UTC-05:00-Kingston",
  "UTC-04:00-Eastern Time US and Canada)",
  "UTC-04:00-Indiana East)",
  "UTC-04:30-Caracas",
  "UTC-03:00-Asuncion",
  "UTC-03:00-Atlantic Time Canada)",
  "UTC-04:00-Cuiaba",
  "UTC-04:00-Georgetown",
  "UTC-02:30-Newfoundland and Labrador",
  "UTC-03:00-Brasilia",
  "UTC-03:00-Buenos Aires",
  "UTC-03:00-Cayenne",
  "UTC-02:00-Greenland",
  "UTC-03:00-Montevide",
  "UTC-03:00-Salvador",
  "UTC-03:00-Santiago",
  "UTC-02:00-Mid-Atlantic",
  "UTC+00:00-Azores",
  "UTC-01:00-Cape Verde Islands",
  "UTC+01:00-Dublin",
  "UTC+01:00-Casablanca",
  "UTC+00:00-Monrovia",
  "UTC+02:00-Amsterdam",
  "UTC+02:00-Belgrade",
  "UTC+02:00-Brussels",
  "UTC+02:00-Sarajevo",
  "UTC+01:00-West Central Africa",
  "UTC+02:00-Windhoek",
  "UTC+03:00-Athen",
  "UTC+03:00-Beirut",
  "UTC+02:00-Cairo",
  "UTC+03:00-Damascus",
  "UTC+03:00-Eastern Europe",
  "UTC+02:00-Harare",
  "UTC+03:00-Helsinki",
  "UTC+03:00-Istanbul",
  "UTC+03:00-Jerusalem",
  "UTC+02:00-Kaliningrad",
  "UTC+02:00-Tripoli",
  "UTC+03:00-Amman",
  "UTC+03:00-Baghdad",
  "UTC+03:00-Kuwait",
  "UTC+03:00-Minsk",
  "UTC+03:00-Moscow",
  "UTC+03:00-Nairobi",
  "UTC+03:30-Tehran",
  "UTC+04:00-Abu Dhabi",
  "UTC+05:00-Baku",
  "UTC+04:00-Izhevsk",
  "UTC+04:00-Port Louis",
  "UTC+04:00-Tbilisi",
  "UTC+04:00-Yerevan",
  "UTC+04:30-Kabul",
  "UTC+05:00-Tashkent",
  "UTC+05:00-Ekaterinburg",
  "UTC+05:00-Islamabad",
  "UTC+05:30-Chennai",
  "UTC+05:30-Sri Jayawardenepura",
  "UTC+05:45-Kathmandu",
  "UTC+06:00-Astana",
  "UTC+06:00-Dhaka",
  "UTC+06:00-Novosibirsk",
  "UTC+06:30-Yangon Rangoon",
  "UTC+07:00-Bangkok",
  "UTC+07:00-Krasnoyarsk",
  "UTC+08:00-Beijing",
  "UTC+08:00-Irkutsk",
  "UTC+08:00-Kuala Lumpur",
  "UTC+08:00-Perth",
  "UTC+08:00-Taipei",
  "UTC+08:00-Ulaanbaatar",
  "UTC+09:00-Osaka",
  "UTC+09:00-Seoul",
  "UTC+09:00-Yakutsk",
  "UTC+10:30-Adelaide",
  "UTC+09:30-Darwin",
  "UTC+10:00-Brisbane",
  "UTC+11:00-Canberra",
  "UTC+10:00-Guam",
  "UTC+11:00-Hobart",
  "UTC+10:00-Magadan",
  "UTC+10:00-Vladivostok",
  "UTC+11:00-Chokirdakh",
  "UTC+11:00-Solomon Islands",
  "UTC+12:00-Anadyr",
  "UTC+13:00-Auckland",
  "UTC+12:00-Fiji Islands",
  "UTC+13:00-Nukualofa",
  "UTC+14:00-Samoa",
];
