export const styles = {
  blue: {
    backgroundColor: "#4F9AFF",
    // height:'100vh',
    display: { md: "block", xs: "none" },
  },
  signup: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  img: {
    marginTop: "24px",
  },
  sinup: {
    fontWeight: 700,
    fontSize: "48px",
    lineHeight: "70px",
    letterSpacing: "1.5px",
    marginTop: { md: "50px", xs: "20px" },
  },
  btncand: {
    border: "1px solid white",
    color: "white",
    width: { lg: "480px" },
    height: { lg: "76px" },
  },
  mntxt: {
    fontSize: "24px",
  },
  sbtxt: {
    fontSize: "16px",
  },
  grid: {
    // marginTop:'60px',
    rowGap: { md: "35px", xs: "15px" },
    paddingRight: "30px",
    paddingLeft: "20px",
  },
  rightbtn: {
    marginTop: "100px",
    paddingBottom: "50px",
    paddingRight: "33px",
    paddingLeft: "33px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: { md: "38px" },
  },
  menu: {
    border: "1px solid grey",
    color: "#7a7d80",
    width: "100%",
    padding: "15px 15px",
    justifyContent: "space-between",
  },
  topspc: {
    display: { md: "none", xs: "flex" },
    paddingBottom: { md: "0", xs: "20px" },
    paddingTop: { md: "0", xs: "20px" },
    justifyContent: "space-evenly",
  },
  topspccon: {
    display: { md: "none", xs: "flex" },
    paddingBottom: { md: "0", xs: "20px" },
    paddingTop: { md: "0", xs: "10px" },
    justifyContent: "space-evenly",
  },
  topbtn: {
    border: "1px solid #fff",
    backgroundColor: "#4F9AFF",
    color: "white",
  },
  candtxt: {
    fontSize: { md: "20px", sm: "16px" },
    fontWeight: "700",
    fontFamily: "GreycliffCF-Bold",
    lineHeight: "35px",
    letterSpacing: "1.5px",
  },
  candsub: {
    fontSize: "16px",
    fontWeight: "400",
    marginTop: "5px",
    marginLeft: "10px",
    fontFamily: "GreycliffCF-Regular",
  },
  card: {
    boxShadow: `30px 50px 21px rgba(33,33,33,.2)`,
    padding: "10px",
    borderRadius: "20px",
  },
  buttonCards: {
    display: "flex",
    gap: "20px",
    flexDirection: { xs: "column", sm: "row" },
    justifyContent: "center",
    mt: "10px",
    alignItems: "center",
  },
  cardContainer: {
    display: "flex",
    gap: "30px",
    flexDirection: "column",
    justifyContent: "center",
    mt: "20px",
  },
  passwordContainer: {
    display: "flex",
    gap: "20px",
    flexDirection: { xs: "column", sm: "row" },
    justifyContent: "center",
  },
  socialContainer: {
    display: "flex",
    flexDirection: "row",
    gap: "40px",
    justifyContent: "center",
  },
  bluetxt: {
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "38px",
    lineHeight: "50px",
    paddingLeft: "68px",
    paddingRight: "29px",
    color: "white",
    // letterSpacing:'1.5px',
  },
  bluemain: {
    marginTop: "50px",
  },
  bluesub: {
    fontWeight: "300",
    fontSize: "23px",
    paddingLeft: "68px",
    paddingRight: "60px",
    color: "white",
    fontFamil: "GreycliffCF-Regular",
    marginTop: "13px",
  },
  btmImgContainer: {
    marginTop: "10px",
  },
  btImage: {
    position: "relative",
    paddingLeft: "74px",
  },
};
